ufc:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: UFC
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: accountadmin
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH
  target: dev
