services:
  dev_env:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ${HOME}/.dbt:/root/.dbt
    env_file:
      - .env
    environment:
      - AWS_DEFAULT_REGION=ap-northeast-1
    command: sleep infinity
